Add connect_handler
KurimuzonAkuma/pyrogram pull request #105
Opened 2024-11-09 09:26 UTC by drizzt

For coherency add also an on_connect handler.

A good use case for this is when you use Smart Plugin, so you can add the initialization code needed for your plugin in the plugin file itself

2024-11-27 13:40 UTC, GPByte commented
This is interesting. Can we ask for this to be included in one of the next versions?

2024-11-27 13:42 UTC, KurimuzonAkuma commented
> This is interesting. Can we ask for this to be included in one of the next versions?

I'm still recovering from surgery, so I haven't really watched much change yet. I'll check in when I'm feeling better

2024-11-27 14:15 UTC, GPByte commented
OMG! I am so sorry!!! I didn't know!!! I wish you all the best! Get well and recover fully! That should be the most important thing!
Best Regards!

2024-11-28 15:51 UTC, KurimuzonAkuma requested changes

2025-05-03 14:50 UTC, merged