network layer
KurimuzonAkuma/pyrogram pull request #95
Opened 2024-10-01 15:16 UTC by deus-developer

2024-10-05 17:02 UTC, KurimuzonAkuma requested changes

2024-11-02 13:47 UTC, Danstiv commented
Hello @deus-developer!
I'm not a pyrogram developer but am interested in some changes and you've made some of them.
For example, I want to refactor the dispatcher, which is what you did in this PR.
In your version of the dispatcher, the parser search logic has been changed, previously a dictionary was used, and you perform search using isinstance.
I did some experimenting and found that this approach was noticeably slower than dictionary lookups, and since this is a key element of the library, I think performance is important here.

- Dictionary lookup takes about 25 ns.
- isinstance check by class - 25 ns.
- isinstance check by tuple (first element) - 25 ns.
- isinstance check by tuple (fifth element) - 70 ns.
- isinstance check by union (first element) - 130 ns.
- isinstance check by union (fifth element) - 215 ns.

So, finding the parser can take more than a microsecond. Instead of a fixed 25 nanoseconds.

Probably it's not a big performance hit, but other than that, 15 elifs in a row doesn't look very good, and it might be worth going back to using a dictionary.

@KurimuzonAkuma 
[code example](https://github.com/user-attachments/files/17607132/isinstance_test.txt)

2024-11-04 19:59 UTC, Danstiv commented
I checked the difference between calling synchronous and asynchronous functions, as expected, asynchronous ones are called slower, the difference is 2.8 times (18 ns vs 50 ns on my machine).
But such a call is performed once when parsing update, so I think that we can degrade performance by 30 ns in some cases and make all parsing methods asynchronous, even if there is only synchronous code inside.
And make them classmethods by the way, why are they static?..

2024-11-10 13:07 UTC, NaNOteh approved these changes

2025-06-10 16:11 UTC, closed without merging